import { useEffect, useState, type FormEvent } from "react";
import { Activity, CheckCircle2, Database, Edit3, History, Save, Server, Settings2, Users, XCircle } from "lucide-react";
import { api, type AuditEvent, type Integration, type Overview, type Tenant } from "../lib/api";

function ErrorBox({ message }: { message: string }) { return <div className="alert error"><XCircle size={16} />{message}</div>; }
function SuccessBox({ message }: { message: string }) { return <div className="alert success"><CheckCircle2 size={16} />{message}</div>; }
function AdminStat({ label, value, icon: Icon, tone = "green" }: { label: string; value: unknown; icon: typeof Activity; tone?: string }) { return <article className={`stat-card ${tone}`}><div className="stat-top"><span>{label}</span><span className="icon-chip"><Icon size={17} /></span></div><strong>{String(value ?? 0)}</strong><small>Dados da plataforma</small></article>; }

export function AdminPage() {
  const [overview, setOverview] = useState<Overview>({}); const [tenants, setTenants] = useState<Tenant[]>([]); const [health, setHealth] = useState<Record<string, string>>({}); const [integrations, setIntegrations] = useState<Integration[]>([]); const [audit, setAudit] = useState<AuditEvent[]>([]); const [busy, setBusy] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [creating, setCreating] = useState(false); const [editing, setEditing] = useState<string | null>(null);
  async function load() { setBusy(true); setError(""); try { const [overviewResult, tenantsResult, healthResult, integrationsResult, auditResult] = await Promise.all([api.admin.overview(), api.admin.tenants(), api.admin.health(), api.admin.integrations(), api.admin.audit()]); setOverview(overviewResult); setTenants(tenantsResult.tenants || []); setHealth(healthResult.services || {}); setIntegrations(integrationsResult.integrations || []); setAudit(auditResult.events || []); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível carregar a administração."); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, []);
  async function createTenant(event: FormEvent) { event.preventDefault(); setCreating(true); setError(""); setNotice(""); try { await api.admin.createTenant(name, email, password); setName(""); setEmail(""); setPassword(""); setNotice("Cliente criado. Já pode iniciar sessão com o email e a palavra-passe definidos."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível criar o cliente."); } finally { setCreating(false); } }
  async function saveIntegration(item: Integration) { setError(""); try { await api.admin.updateIntegration(item.key, { label: item.label, public_url: item.public_url, notes: item.notes }); setNotice(`Integração ${item.label} atualizada.`); setEditing(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível guardar a integração."); } }
  function patchIntegration(key: string, field: "label" | "public_url" | "notes", value: string) { setIntegrations((current) => current.map((item) => item.key === key ? { ...item, [field]: value } : item)); }
  return <div className="content-stack"><div className="module-header"><div><span className="eyebrow">GESTÃO DA PLATAFORMA</span><h1>Administração</h1><p>Controla clientes, integrações, auditoria e saúde da infraestrutura.</p></div><button className="secondary-button" onClick={() => void load()}><Activity size={16} /> Atualizar</button></div>{error && <ErrorBox message={error} />}{notice && <SuccessBox message={notice} />}<section className="stat-grid"><AdminStat label="Clientes" value={overview.tenants} icon={Users} /><AdminStat label="Utilizadores" value={overview.users} icon={Activity} tone="blue" /><AdminStat label="Ativos" value={overview.active_tenants} icon={CheckCircle2} tone="violet" /></section>
    <div className="module-grid two"><section className="data-panel"><div className="panel-heading"><div><span className="eyebrow">TENANTS</span><h3>Clientes registados</h3></div><Users size={19} /></div>{busy ? <div className="loading-box">A carregar clientes...</div> : tenants.length ? <div className="data-list">{tenants.map((tenant) => <div className="data-row" key={tenant.id}><div className="avatar">{tenant.name.slice(0, 1).toUpperCase()}</div><div className="row-main"><strong>{tenant.name}</strong><small>{tenant.id} · {tenant.plan || "demonstração"}</small></div><span className={`status-badge ${tenant.status || "active"}`}>{tenant.status || "active"}</span></div>)}</div> : <div className="empty-state">Ainda não existem clientes.</div>}</section><section className="data-panel"><div className="panel-heading"><div><span className="eyebrow">NOVO CLIENTE</span><h3>Criar acesso</h3></div><Users size={19} /></div><form className="stack-form compact-form" onSubmit={createTenant}><label>Nome<input value={name} onChange={(event) => setName(event.target.value)} required /></label><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Palavra-passe<input type="password" minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} required /></label><button className="primary-button" disabled={creating} type="submit">{creating ? "A criar..." : "Criar cliente"}</button></form></section></div>
    <section className="data-panel"><div className="panel-heading"><div><span className="eyebrow">INFRAESTRUTURA</span><h3>Saúde dos serviços</h3></div><Server size={19} /></div><div className="health-list">{Object.entries(health).map(([key, value]) => <div className="health-item" key={key}><span className="status-dot" /><div className="row-main"><strong>{key === "firestore" ? "Firebase / Firestore" : key === "evolution" ? "Evolution API" : key === "redis" ? "Redis Queue" : key}</strong><small>{value}</small></div></div>)}{!Object.keys(health).length && <div className="empty-state">Sem dados de saúde.</div>}</div></section>
    <section className="data-panel"><div className="panel-heading"><div><span className="eyebrow">INTEGRAÇÕES</span><h3>Configuração operacional</h3></div><Settings2 size={19} /></div><div className="data-list">{integrations.map((item) => <div className="data-row integration-row" key={item.key}><div className="quick-icon"><Database size={16} /></div><div className="row-main">{editing === item.key ? <><input value={item.label} onChange={(event) => patchIntegration(item.key, "label", event.target.value)} /><input value={item.public_url || ""} onChange={(event) => patchIntegration(item.key, "public_url", event.target.value)} placeholder="URL pública opcional" /><input value={item.notes || ""} onChange={(event) => patchIntegration(item.key, "notes", event.target.value)} placeholder="Notas" /></> : <><strong>{item.label}</strong><small>{item.kind || item.key} · {item.configured ? "configurada" : "por configurar"}</small></>}</div>{editing === item.key ? <button title="Guardar" onClick={() => void saveIntegration(item)}><Save size={14} /></button> : <button title="Editar" onClick={() => setEditing(item.key)}><Edit3 size={14} /></button>}</div>)}</div></section>
    <section className="data-panel"><div className="panel-heading"><div><span className="eyebrow">AUDITORIA</span><h3>Últimos eventos</h3></div><History size={19} /></div>{audit.length ? <div className="data-list">{audit.slice(0, 50).map((event) => <div className="data-row" key={event.id}><div className="quick-icon"><History size={16} /></div><div className="row-main"><strong>{event.event || "evento"}</strong><small>{event.actor_role || "sistema"} · {event.tenant_id || "global"}</small></div><small className="muted">{event.created_at ? new Date(event.created_at).toLocaleString("pt-PT") : ""}</small></div>)}</div> : <div className="empty-state">Ainda não existem eventos de auditoria.</div>}</section>
  </div>;
}
