import os

class Config:
    TIMEOUT_HUMANO_MINUTOS = int(os.getenv('TIMEOUT_HUMANO_MINUTOS', 2))
    GROQ_API_KEY = os.getenv('GROQ_API_KEY')
    GROQ_MODEL = os.getenv('GROQ_MODEL', 'llama-3.3-70b-versatile')
    GROQ_VISION_MODEL = os.getenv('GROQ_VISION_MODEL', 'qwen-2.5-32b')
    NUMERO_ASSISTANTE = os.getenv('ASSISTANT_NUMBER')
    ADMIN_NUMBER = os.getenv('ADMIN_NUMBER')
    EVOLUTION_API_KEY = os.getenv('EVOLUTION_API_KEY')
    EVOLUTION_API_URL = os.getenv('EVOLUTION_API_URL')
    EVOLUTION_INSTANCE_NAME = os.getenv('EVOLUTION_INSTANCE_NAME')
    WEBHOOK_URL = os.getenv('WEBHOOK_URL')
    FIREBASE_CONFIG = os.getenv('FIREBASE_CONFIG')
    N8N_CAMPAIGN_WEBHOOK_URL = os.getenv('N8N_CAMPAIGN_WEBHOOK_URL')
    N8N_WEBHOOK_SECRET = os.getenv('N8N_WEBHOOK_SECRET')
    N8N_WEBHOOK_TIMEOUT = int(os.getenv('N8N_WEBHOOK_TIMEOUT', '12'))
    N8N_WEBHOOK_RETRIES = int(os.getenv('N8N_WEBHOOK_RETRIES', '3'))
    AI_PRIMARY_TIMEOUT = int(os.getenv('AI_PRIMARY_TIMEOUT', '4'))
    AI_FALLBACK_TIMEOUT = int(os.getenv('AI_FALLBACK_TIMEOUT', '8'))
    REDIS_URL = os.getenv('REDIS_URL', 'redis://redis:6379/1')
    WHATSAPP_INCOMING_QUEUE = os.getenv('WHATSAPP_INCOMING_QUEUE', 'whatsapp_incoming_queue')
    AI_QUEUE_MAX_PER_SECOND = int(os.getenv('AI_QUEUE_MAX_PER_SECOND', '15'))
    CEREBRAS_API_KEY = os.getenv('CEREBRAS_API_KEY')
    CEREBRAS_MODEL = os.getenv('CEREBRAS_MODEL', 'llama3.3-70b')
    SAMBANOVA_API_KEY = os.getenv('SAMBANOVA_API_KEY')
    SAMBANOVA_MODEL = os.getenv('SAMBANOVA_MODEL', 'Meta-Llama-3.3-70B-Instruct')
    GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
    GEMINI_API_KEY_2 = os.getenv('GEMINI_API_KEY_2')
    GEMINI_MODEL = os.getenv('GEMINI_MODEL', 'gemini-2.0-flash')
    GEMINI_MODEL_2 = os.getenv('GEMINI_MODEL_2', 'gemini-2.0-flash')
    GITHUB_MODELS_TOKEN = os.getenv('GITHUB_MODELS_TOKEN')
    GITHUB_MODELS_MODEL = os.getenv('GITHUB_MODELS_MODEL', 'Llama-3.3-70B-Instruct')
    MISTRAL_API_KEY = os.getenv('MISTRAL_API_KEY')
    MISTRAL_MODEL = os.getenv('MISTRAL_MODEL', 'mistral-small-latest')
    OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY')
    OPENROUTER_MODEL = os.getenv('OPENROUTER_MODEL', 'openrouter/free')
