import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { BrowserRouter, Navigate, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import { Activity, Bot, Building2, CheckCircle2, ChevronRight, CircleDollarSign, LayoutDashboard, LogOut, MessageCircle, QrCode, Send, Settings2, Smartphone, Users, Wifi, X } from "lucide-react";
import { api, type AuthState, type ClientPlan, type IntegrationStatus, type Overview, type PlatformUser } from "./lib/api";
import { AdminPage } from "./pages/AdminPage";
import { AssistantPage, BillingPage, BusinessProfilePage, CampaignsPage, ConversationsPage, MetricsPage, SupportPage, TeamPage, VideoPage, WhatsAppPage } from "./pages/ClientPages";
import { PublicAssistantPage, PublicSite } from "./pages/PublicSite";

type AuthContextValue = { auth: AuthState; refresh: () => Promise<void>; logout: () => Promise<void> };
const defaultAuth: AuthState = { authenticated: false, user: null };

function LoginPage({ onLogin }: { onLogin: (user: PlatformUser) => void }) {
  const [identifier, setIdentifier] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setBusy(true); try { const result = await api.auth.login(identifier, password); onLogin(result.user); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível iniciar a sessão."); } finally { setBusy(false); } }
  return <main className="auth-shell"><section className="auth-card"><div className="brand-mark">N</div><span className="eyebrow">NEGOBOT-MOZ</span><h1>Centro de automação WhatsApp</h1><p className="muted">Acede ao teu espaço de gestão com segurança.</p><form onSubmit={submit} className="stack-form"><label>Email ou identificador<input value={identifier} onChange={(event) => setIdentifier(event.target.value)} placeholder="email@empresa.co.mz ou admin" autoComplete="username" /></label><label>Palavra-passe<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Introduz a palavra-passe" autoComplete="current-password" /></label>{error && <div className="alert error"><X size={16} />{error}</div>}<button className="primary-button" disabled={busy} type="submit">{busy ? "A autenticar..." : "Entrar na plataforma"}</button></form><p className="auth-footnote">Os dados de cada cliente são isolados por tenant.</p><p className="auth-footnote">Ainda não tens conta? <a href="/plataforma/register" style={{ color: "#8ce7b8" }}>Começa a demonstração de 2 dias</a>.</p></section></main>;
}

function RegisterPage({ onRegister }: { onRegister: (user: PlatformUser) => void }) {
  const params = new URLSearchParams(window.location.search);
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState("");
  const [region, setRegion] = useState<"mozambique" | "international">(params.get("region") === "international" ? "international" : "mozambique");
  const [planId, setPlanId] = useState(params.get("plan") || "basico"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const loginPath = window.location.pathname.startsWith("/plataforma-react") ? "/plataforma-react/login" : "/plataforma/login";
  async function submit(event: FormEvent) {
    event.preventDefault(); setError("");
    if (password !== confirmPassword) { setError("As palavras-passe não coincidem."); return; }
    setBusy(true);
    try { const result = await api.auth.register({ name, email, password, billing_region: region, plan_id: planId }); onRegister(result.user); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível criar a conta."); }
    finally { setBusy(false); }
  }
  return <main className="auth-shell"><section className="auth-card"><div className="brand-mark">N</div><span className="eyebrow">COMEÇA COM NEGOBOT-MOZ</span><h1>Cria o teu espaço de demonstração</h1><p className="muted">Testa durante 2 dias. O contador só começa quando o teu WhatsApp ficar ligado.</p><form onSubmit={submit} className="stack-form"><label>Empresa ou nome<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Nome da empresa" autoComplete="organization" required /></label><label>Email de acesso<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="email@empresa.com" autoComplete="email" required /></label><label>Palavra-passe<input type="password" minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Mínimo de 8 caracteres" autoComplete="new-password" required /></label><label>Confirmar palavra-passe<input type="password" minLength={8} value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} placeholder="Repete a palavra-passe" autoComplete="new-password" required /></label><label>Onde vais pagar?<select value={region} onChange={(event) => setRegion(event.target.value as "mozambique" | "international")}><option value="mozambique">Moçambique · M-Pesa para 855000929</option><option value="international">Outro país · cartão/PayPal via Lemon Squeezy</option></select></label><label>Plano de interesse<select value={planId} onChange={(event) => setPlanId(event.target.value)}><option value="basico">Básico · 500 MT / 30 dias</option><option value="medio">Médio · 1.000 MT / 30 dias</option><option value="premium">Premium · 1.500 MT / 30 dias</option></select></label>{error && <div className="alert error"><X size={16} />{error}</div>}<button className="primary-button" disabled={busy} type="submit">{busy ? "A criar o espaço..." : "Criar conta e começar"}</button></form><p className="auth-footnote">Depois de entrar: completa o perfil, liga o WhatsApp e acompanha o trial na plataforma.</p><p className="auth-footnote">Já tens conta? <a href={loginPath} style={{ color: "#8ce7b8" }}>Entrar na plataforma</a>.</p></section></main>;
}
function ProtectedRoute({ auth, children }: { auth: AuthState; children: ReactNode }) { if (!auth.authenticated) return <Navigate to="/login" replace />; return <>{children}</>; }

function AppShell({ user, onLogout, children }: { user: PlatformUser; onLogout: () => void; children: ReactNode }) {
  const location = useLocation(); const navigate = useNavigate(); const isAdmin = user.role === "owner" || user.role === "admin";
  const navigation = [{ label: "Visão geral", path: "/", icon: LayoutDashboard }, { label: "Conversas", path: "/conversas", icon: MessageCircle }, { label: "Campanhas", path: "/campanhas", icon: Send },  { label: "WhatsApp", path: "/whatsapp", icon: QrCode }, { label: "Empresa e redes", path: "/empresa", icon: Building2 }, { label: "Equipa", path: "/equipa", icon: Users },
 { label: "Assistente", path: "/assistente", icon: Bot }, { label: "Métricas", path: "/metricas", icon: Activity }, { label: "Vídeos", path: "/videos", icon: Send }, { label: "Suporte", path: "/suporte", icon: MessageCircle },
 { label: "Plano e pagamentos", path: "/plano", icon: CircleDollarSign }, ...(isAdmin ? [{ label: "Administração", path: "/admin", icon: Settings2 }] : [])];
  return <div className="app-frame"><aside className="sidebar"><button className="brand-lockup" onClick={() => navigate("/")}><span className="brand-mark small">N</span><span><strong>NEGOBOT</strong><small>MOZ PLATFORM</small></span></button><div className="workspace-card"><span className="status-dot" />{isAdmin ? "Visão do administrador" : "Espaço do cliente"}</div><nav className="sidebar-nav"><span className="nav-heading">Plataforma</span>{navigation.map(({ label, path, icon: Icon }) => <button key={path} className={`nav-item ${location.pathname === path ? "active" : ""}`} onClick={() => navigate(path)}><Icon size={18} /><span>{label}</span><ChevronRight size={14} className="nav-chevron" /></button>)}</nav><div className="sidebar-bottom"><div className="user-mini"><div className="avatar">{(user.name || "N").slice(0, 1).toUpperCase()}</div><div><strong>{user.name}</strong><small>{user.role}</small></div></div><button className="nav-item logout" onClick={onLogout}><LogOut size={18} /><span>Sair</span></button></div></aside><div className="main-column"><header className="topbar"><div><span className="eyebrow">ESPAÇO DE GESTÃO</span><h2>Olá, {user.name.split(" ")[0]}</h2></div><div className="topbar-actions"><div className="live-pill"><span className="status-dot" /> Sistema operacional</div><div className="avatar large">{(user.name || "N").slice(0, 1).toUpperCase()}</div></div></header><main className="page-content">{children}</main></div></div>;
}
function StatCard({ label, value, caption, icon: Icon, tone = "green" }: { label: string; value: string; caption: string; icon: typeof Activity; tone?: string }) { return <article className={`stat-card ${tone}`}><div className="stat-top"><span>{label}</span><span className="icon-chip"><Icon size={17} /></span></div><strong>{value}</strong><small>{caption}</small></article>; }
function OverviewPage({ user }: { user: PlatformUser }) {
  const [overview, setOverview] = useState<Overview>({}); const [plan, setPlan] = useState<ClientPlan | null>(null); const [integration, setIntegration] = useState<IntegrationStatus | null>(null); const [loading, setLoading] = useState(true); const isAdmin = user.role === "owner" || user.role === "admin";
  useEffect(() => { let cancelled = false; async function load() { try { if (isAdmin) { const result = await api.admin.overview(); if (!cancelled) setOverview(result); } else { const [overviewResult, planResult, integrationResult] = await Promise.all([api.client.overview(), api.client.plan(), api.client.integrationStatus()]); if (!cancelled) { setOverview(overviewResult); setPlan(planResult); setIntegration(integrationResult); } } } finally { if (!cancelled) setLoading(false); } } void load(); return () => { cancelled = true; }; }, [isAdmin]);
  const status = integration?.state || "desconectado";
  return <div className="content-stack"><section className="hero-panel"><div><span className="eyebrow">PAINEL PRINCIPAL</span><h1>{isAdmin ? "Controlo central da plataforma" : "A tua automação num só lugar"}</h1><p>{isAdmin ? "Acompanha clientes, integrações e operação sem sair deste centro." : "Gere contactos, campanhas e o teu assistente WhatsApp com uma experiência simples."}</p></div><div className="hero-orb"><Bot size={54} /></div></section><section className="stat-grid">{isAdmin ? <><StatCard label="Clientes" value={loading ? "—" : String(overview.tenants || 0)} caption="Tenants registados" icon={Users} /><StatCard label="Utilizadores" value={loading ? "—" : String(overview.users || 0)} caption="Contas da plataforma" icon={Activity} tone="blue" /><StatCard label="Ativos" value={loading ? "—" : String(overview.active_tenants || 0)} caption="Clientes em operação" icon={CheckCircle2} tone="violet" /></> : <><StatCard label="Plano atual" value={plan?.plan_name || "Demonstração"} caption={plan?.status || "A carregar estado"} icon={CircleDollarSign} /><StatCard label="Contactos" value={loading ? "—" : String(overview.contacts || 0)} caption="Contactos com opt-in" icon={Users} tone="blue" /><StatCard label="WhatsApp" value={status === "open" ? "Ligado" : "Não ligado"} caption={integration?.instance_name || "Liga o teu número"} icon={Wifi} tone={status === "open" ? "blue" : "amber"} /></>}</section><section className="section-heading"><div><span className="eyebrow">ACESSO RÁPIDO</span><h3>Continua o teu trabalho</h3></div></section><section className="quick-grid"><QuickAction icon={MessageCircle} title="Conversas" text="Acompanha e responde aos teus contactos." path="/conversas" /><QuickAction icon={QrCode} title="Ligar WhatsApp" text="Gera o QR Code da tua instância." path="/whatsapp" /><QuickAction icon={CircleDollarSign} title="Plano e pagamentos" text="Consulta benefícios e valida M-Pesa." path="/plano" /></section></div>;
}
function QuickAction({ icon: Icon, title, text, path }: { icon: typeof MessageCircle; title: string; text: string; path: string }) { const navigate = useNavigate(); return <button className="quick-card" onClick={() => navigate(path)}><span className="quick-icon"><Icon size={22} /></span><span><strong>{title}</strong><small>{text}</small></span><ChevronRight size={17} /></button>; }
function PlatformRouter({ user, onLogout }: { user: PlatformUser; onLogout: () => void }) { return <AppShell user={user} onLogout={onLogout}><Routes><Route index element={<OverviewPage user={user} />} /><Route path="conversas" element={<ConversationsPage />} /><Route path="campanhas" element={<CampaignsPage />} /><Route path="whatsapp" element={<WhatsAppPage />} /><Route path="empresa" element={<BusinessProfilePage />} /><Route path="equipa" element={<TeamPage />} />
<Route path="assistente" element={<AssistantPage />} /><Route path="metricas" element={<MetricsPage />} /><Route path="videos" element={<VideoPage />} /><Route path="suporte" element={<SupportPage />} />
<Route path="plano" element={<BillingPage />} /><Route path="admin" element={(user.role === "owner" || user.role === "admin") ? <AdminPage /> : <Navigate to="/" replace />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></AppShell>; }

function PlatformApp() {
  const appBasePath = window.location.pathname.startsWith("/plataforma-react") ? "/plataforma-react" : "/plataforma"; const [auth, setAuth] = useState<AuthState>(defaultAuth); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; const timeout = new Promise<AuthState>((resolve) => window.setTimeout(() => resolve(defaultAuth), 8000)); Promise.race([api.auth.me(), timeout]).then((result) => { if (active) setAuth(result); }).catch(() => { if (active) setAuth(defaultAuth); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const authValue = useMemo(() => ({ auth, refresh: async () => setAuth(await api.auth.me()), logout: async () => { await api.auth.logout(); setAuth(defaultAuth); } }), [auth]);
  if (loading) return <main className="loading-shell"><div className="spinner" /><span>A carregar a plataforma...</span></main>;
  return <BrowserRouter basename={appBasePath}><Routes><Route path="/login" element={auth.authenticated ? <Navigate to="/" replace /> : <LoginPage onLogin={(user) => setAuth({ authenticated: true, user })} />} /><Route path="/register" element={auth.authenticated ? <Navigate to="/" replace /> : <RegisterPage onRegister={(user) => setAuth({ authenticated: true, user })} />} /><Route path="/*" element={<ProtectedRoute auth={auth}><PlatformRouter user={authValue.auth.user!} onLogout={() => void authValue.logout()} /></ProtectedRoute>} /></Routes></BrowserRouter>;
}

export default function App() {
  const path = window.location.pathname;
  if (path === "/assistente" || path === "/assistente/") return <PublicAssistantPage />;
  if (!path.startsWith("/plataforma")) return <PublicSite />;
  return <PlatformApp />;
}
